"""empty message

Revision ID: 2519b723c0d6
Revises: 6bafedc34a7b
Create Date: 2021-08-05 14:04:33.834565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2519b723c0d6'
down_revision = '6bafedc34a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=200), nullable=True))
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('user', 'pin',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pin',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
