"""empty message

Revision ID: 89f24dcfb6c8
Revises: ed3a2fbbc5be
Create Date: 2021-07-10 10:52:18.304141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f24dcfb6c8'
down_revision = 'ed3a2fbbc5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timestamp')
    # ### end Alembic commands ###
